version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-python-3.6
      - test-python-3.7
      - test-python-3.8
      - test-python-3.9
jobs:
  test-python-3.6: &build-template
    working_directory: ~/SunPower/pvfactors
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: cimg/python:3.6.15
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: sudo apt-get update
      - run: sudo apt-get install -y pandoc
      - run: python --version
      - run: pip install --upgrade pip setuptools wheel
      - run: pip --version
      - run: pip install --progress-bar=off .[testing,docs]
      - run: python setup.py build_sphinx
      - run: pytest --junitxml=$CIRCLE_TEST_REPORTS/junit.xml
      - store_test_results:
          path: $CIRCLE_TEST_REPORTS
      - store_artifacts:
          path: $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: $CIRCLE_TEST_REPORTS
      - store_artifacts:
          path: build/sphinx/html
          destination: docs
  test-python-3.7:
    <<: *build-template
    docker:
      - image: cimg/python:3.7.12
  test-python-3.8:
    <<: *build-template
    docker:
      - image: cimg/python:3.8.12
  test-python-3.9:
    <<: *build-template
    docker:
      - image: cimg/python:3.9.6
