version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-python-2.7
      - test-python-3.5
      - test-python-3.6
      - test-python-3.7
jobs:
  test-python-2.7: &build-template
    working_directory: ~/SunPower/pvfactors
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/python:2.7.14-stretch
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run: sudo apt-get install -y pandoc
      - run: sudo pip install --progress-bar=off .[testing,docs]
      - run: python setup.py build_sphinx
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - ~/virtualenvs
            - ~/.m2
            - ~/.ivy2
            - ~/.bundle
            - ~/.go_workspace
            - ~/.gradle
            - ~/.cache/bower
      - run: pytest
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: build/sphinx/html
          destination: docs
  test-python-3.5:
    <<: *build-template
    docker:
      - image: circleci/python:3.5.7-stretch
  test-python-3.6:
    <<: *build-template
    docker:
      - image: circleci/python:3.6.6-stretch
  test-python-3.7:
    <<: *build-template
    docker:
      - image: circleci/python:3.7.3-stretch
